version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: bezkoder
      POSTGRES_PASSWORD: bez123
      POSTGRES_DB: bezkoder_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bezkoder -d bezkoder_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app_net

  spring-boot:
    build:
      context: ./spring-boot-server
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bezkoder_db
      SPRING_DATASOURCE_USERNAME: bezkoder
      SPRING_DATASOURCE_PASSWORD: bez123
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: '*'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      start_period: 40s
      retries: 5

  angular:
    build:
      context: ./angular-17-client
      dockerfile: Dockerfile
    ports:
      - "4203:80"
    depends_on:
      spring-boot:
        condition: service_healthy
    networks:
      - app_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./docker/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/prometheus/config/alert-rules.yml:/etc/prometheus/alert-rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - alertmanager
    networks:
      - app_net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./docker/alert-manager/config.yml:/etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    networks:
      - app_net

  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana-storage:/var/lib/grafana
    networks:
      - app_net

  nginx:
    build:
      context: .

      dockerfile: angular-17-client/Dockerfile
    ports:
      - "81:80"
    depends_on:
      spring-boot:
        condition: service_healthy
    networks:
      - app_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dev.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - app_net

volumes:
  postgres_data:
  pgadmin_data:
  grafana-storage:

networks:
  app_net:
    driver: bridge
