version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: bezkoder
      POSTGRES_PASSWORD: bez123
      POSTGRES_DB: bezkoder_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Changé de 5432 -> 5433 (host)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bezkoder -d bezkoder_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app_net

  spring-boot:
    build:
      context: ./spring-boot-server
      dockerfile: Dockerfile
    ports:
      - "8084:8080"  # Changé de 8083 -> 8084 (host)
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bezkoder_db
      SPRING_DATASOURCE_USERNAME: bezkoder
      SPRING_DATASOURCE_PASSWORD: bez123
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: '*'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      start_period: 40s
      retries: 5

  angular:
    build:
      context: ./angular-17-client
      dockerfile: Dockerfile
    ports:
      - "4203:80"  # Changé de 4202 -> 4203 (host)
    depends_on:
      spring-boot:
        condition: service_healthy
    networks:
      - app_net
  nginx:
    image: nginx:alpine
    ports:
      - "81:80"  # Changé de 80 -> 81 (host)
    volumes:
      - ./angular-17-client/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      angular:
        condition: service_started
      spring-boot:
        condition: service_healthy
    networks:
      - app_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5051:80"  # Changé de 5050 -> 5051 (host)
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dev.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - app_net

volumes:
  postgres_data:
  pgadmin_data:
  grafana-storage:

networks:
  app_net:
    driver: bridge
