version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: bezkoder_db
      POSTGRES_USER: bezkoder
      POSTGRES_PASSWORD: bez123
    ports:
      - "5434:5432"  
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    networks:
      - test-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bezkoder -d bezkoder_db"]
      interval: 2s
      timeout: 3s
      retries: 10

  springboot:
    build:
      context: ./spring-boot-server
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bezkoder_db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - test-net
    entrypoint: ["sh", "-c", "java -jar /app.jar"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-test-data:

networks:
  test-net:
