services:
  postgres:
    image: postgres:13
    container_name: test-postgres
    environment:
      POSTGRES_DB: bezkoder_db
      POSTGRES_USER: bezkoder
      POSTGRES_PASSWORD: bez123
    ports:
      - "5432:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    networks:
      - test-net

  springboot:
    build:
      context: ./spring-boot-server
      dockerfile: Dockerfile
    container_name: test-springboot
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bezkoder_db
      SPRING_DATASOURCE_USERNAME: bezkoder
      SPRING_DATASOURCE_PASSWORD: bez123
    depends_on:
      - postgres
    entrypoint: ["java", "-jar", "/app.jar"]
    networks:
      - test-net

volumes:
  postgres-test-data:

networks:
  test-net:
