version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: bezkoder
      POSTGRES_PASSWORD: bez123
      POSTGRES_DB: ezkoder_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  spring-boot:
    build:
      context: ./spring-boot-server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ezkoder_db
      SPRING_DATASOURCE_USERNAME: bezkoder
      SPRING_DATASOURCE_PASSWORD: bez123
    depends_on:
      postgres:
        condition: service_healthy

  angular:
    build:
      context: ./angular-17-client
    ports:
      - "4200:80"
    depends_on:
      - spring-boot

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./angular-17-client/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - angular
      - spring-boot

volumes:
  postgres_data: