version: '3'

services:
  spring-boot:
    build:
      context: ~/spring-boot-angular-17-postgresql-example/spring-boot-server
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ezkoder_db
      SPRING_DATASOURCE_USERNAME: bezkoder
      SPRING_DATASOURCE_PASSWORD: bez123
    depends_on:
      - postgres

  angular:
    build:
      context: ~/spring-boot-angular-17-postgresql-example/angular-17-client
    ports:
      - "4201:80"
    depends_on:
      - spring-boot

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: bezkoder
      POSTGRES_PASSWORD: bez123
      POSTGRES_DB: ezkoder_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./angular-17-client/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - angular
      - spring-boot


volumes:
  postgres_data:
