apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2  # Utilise le deuxième groupe de capture dans la regex
spec:
  ingressClassName: nginx
  rules:
  - host: springboot.local  # Ou l'URL que tu utilises pour accéder à ton app
    http:
      paths:
      - path: /  # Correspond à la racine pour le frontend
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /api/(.*)  # Utilisation de regex pour la route /api
        pathType: ImplementationSpecific  # Nécessaire pour activer le support des regex
        backend:
          service:
            name: backend-service
            port:
              number: 8080
